<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="neza" failures="1" tests="1" name="Default test(failed)" time="0.088" errors="0" timestamp="2022-12-02T18:00:18 CAT">
  <testcase classname="paraunity.Fc" name="contructorshoulstit" time="0.016">
    <failure type="java.lang.AssertionError" message="expected [4] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [0]
at paraunity.Fc.contructorshoulstit(Fc.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- contructorshoulstit -->
</testsuite> <!-- Default test(failed) -->
